export const en = {
  login: 'Login', loginId: 'Login ID', password: 'Password', loginButton: 'Sign In', loginError: 'Invalid login or password', loggingIn: 'Signing in...', adminPanel: 'Admin Panel', botAdminPanel: 'Bot Admin Panel', welcomeBack: 'Welcome back', enterCredentials: 'Enter your login credentials',
  dashboard: 'Dashboard', users: 'Users', broadcast: 'Broadcast', statistics: 'Statistics', channels: 'Channels', prices: 'Prices', commands: 'Commands', settings: 'Settings', logout: 'Logout',
  totalUsers: 'Total Users', activeToday: 'Active Today', bannedUsers: 'Banned Users', messagesSent: 'Messages Sent', recentActivity: 'Recent Activity', quickStats: 'Quick Stats', newToday: 'New Today', totalPayments: 'Total Payments',
  searchUsers: 'Search (username, ID)', userId: 'Telegram ID', username: 'Username', firstName: 'First Name', lastName: 'Last Name', status: 'Status', joinDate: 'Join Date', lastActive: 'Last Active', actions: 'Actions', ban: 'Ban', unban: 'Unban', delete: 'Delete', viewDetails: 'View Details', banned: 'Banned', active: 'Active', deleted: 'Deleted', banReason: 'Ban Reason', confirmBan: 'Do you want to ban this user?', confirmUnban: 'Do you want to unban this user?', confirmDelete: 'Do you want to delete this user?', confirm: 'Confirm', cancel: 'Cancel', userDetails: 'User Details', totalCommands: 'Total Commands', language: 'Language', allUsers: 'All', bannedOnly: 'Banned', activeOnly: 'Active', noUsers: 'No users found', page: 'Page', of: 'of', previous: 'Previous', next: 'Next', showing: 'Showing', results: 'results',
  newBroadcast: 'New Broadcast', messageText: 'Message Text', mediaType: 'Media Type', noMedia: 'No Media', photo: 'Photo', video: 'Video', document: 'Document', audio: 'Audio', mediaUrl: 'Media URL', captionText: 'Caption (optional)', sendBroadcast: 'Send Broadcast', broadcastHistory: 'Broadcast History', broadcastStatus: 'Status', pending: 'Pending', sending: 'Sending', completed: 'Completed', failed: 'Failed', sentCount: 'Sent', failedCount: 'Failed', totalRecipients: 'Total Recipients', broadcastDate: 'Date', sendingBroadcast: 'Sending messages...', broadcastSent: 'Messages sent successfully', enterMessage: 'Enter your message text',
  dailyStats: 'Daily Statistics', monthlyStats: 'Monthly Statistics', userGrowth: 'User Growth', commandStats: 'Command Statistics', peakHours: 'Peak Hours', last7days: 'Last 7 Days', last30days: 'Last 30 Days', newUsers: 'New Users', activeUsers: 'Active Users', commandsUsed: 'Commands Used',
  requiredChannels: 'Required Channels', addChannel: 'Add Channel', channelId: 'Channel ID', channelName: 'Channel Name', channelLink: 'Channel Link', channelStatus: 'Status', editChannel: 'Edit', deleteChannel: 'Delete', confirmDeleteChannel: 'Do you want to delete this channel?', saveChannel: 'Save', noChannels: 'No channels found',
  coursePrices: 'Course Prices', addPrice: 'Add Price', courseName: 'Course Name', description: 'Description', price: 'Price', currency: 'Currency', duration: 'Duration (days)', editPrice: 'Edit', deletePrice: 'Delete', savePrice: 'Save', noPrices: 'No prices found',
  botCommands: 'Bot Commands', addCommand: 'Add Command', command: 'Command', descriptionUz: 'Description (UZ)', descriptionRu: 'Description (RU)', descriptionEn: 'Description (EN)', responseUz: 'Response (UZ)', responseRu: 'Response (RU)', responseEn: 'Response (EN)', usageCount: 'Usage Count', editCommand: 'Edit', deleteCommand: 'Delete', saveCommand: 'Save', noCommands: 'No commands found',
  botSettings: 'Bot Settings', botInfo: 'Bot Information', adminsList: 'Administrators', addAdmin: 'Add Admin', adminName: 'Name', adminLoginId: 'Login ID', adminPassword: 'Password', adminTelegram: 'Telegram Username', saveSettings: 'Save', settingsSaved: 'Settings saved', deleteAdmin: 'Delete Admin', confirmDeleteAdmin: 'Do you want to delete this administrator?',
  save: 'Save', edit: 'Edit', close: 'Close', loading: 'Loading...', error: 'Error', success: 'Success', noData: 'No data', refresh: 'Refresh', total: 'Total', enabled: 'Enabled', disabled: 'Disabled', yes: 'Yes', no: 'No', add: 'Add', update: 'Update', back: 'Back', from: 'from', to: 'to', today: 'Today', yesterday: 'Yesterday',
};
