export const ru = {
  login: 'Войти', loginId: 'Логин', password: 'Пароль', loginButton: 'Войти', loginError: 'Неверный логин или пароль', loggingIn: 'Вход...', adminPanel: 'Панель администратора', botAdminPanel: 'Панель управления ботом', welcomeBack: 'Добро пожаловать', enterCredentials: 'Введите ваш логин и пароль',
  dashboard: 'Главная', users: 'Пользователи', broadcast: 'Рассылка', statistics: 'Статистика', channels: 'Каналы', prices: 'Цены', commands: 'Команды', settings: 'Настройки', logout: 'Выход',
  totalUsers: 'Всего пользователей', activeToday: 'Активны сегодня', bannedUsers: 'Заблокированы', messagesSent: 'Отправлено сообщений', recentActivity: 'Последняя активность', quickStats: 'Быстрая статистика', newToday: 'Новых сегодня', totalPayments: 'Всего платежей',
  searchUsers: 'Поиск (username, ID)', userId: 'Telegram ID', username: 'Username', firstName: 'Имя', lastName: 'Фамилия', status: 'Статус', joinDate: 'Дата вступления', lastActive: 'Последняя активность', actions: 'Действия', ban: 'Заблокировать', unban: 'Разблокировать', delete: 'Удалить', viewDetails: 'Подробнее', banned: 'Заблокирован', active: 'Активный', deleted: 'Удалён', banReason: 'Причина блокировки', confirmBan: 'Вы хотите заблокировать пользователя?', confirmUnban: 'Вы хотите разблокировать пользователя?', confirmDelete: 'Вы хотите удалить пользователя?', confirm: 'Подтвердить', cancel: 'Отмена', userDetails: 'Данные пользователя', totalCommands: 'Всего команд', language: 'Язык', allUsers: 'Все', bannedOnly: 'Заблокированные', activeOnly: 'Активные', noUsers: 'Пользователи не найдены', page: 'Страница', of: 'из', previous: 'Назад', next: 'Далее', showing: 'Показано', results: 'результатов',
  newBroadcast: 'Новое сообщение', messageText: 'Текст сообщения', mediaType: 'Тип медиа', noMedia: 'Без медиа', photo: 'Фото', video: 'Видео', document: 'Документ', audio: 'Аудио', mediaUrl: 'URL медиа', captionText: 'Подпись (необязательно)', sendBroadcast: 'Отправить', broadcastHistory: 'История рассылок', broadcastStatus: 'Статус', pending: 'Ожидание', sending: 'Отправка', completed: 'Завершено', failed: 'Ошибка', sentCount: 'Отправлено', failedCount: 'Ошибок', totalRecipients: 'Всего получателей', broadcastDate: 'Дата', sendingBroadcast: 'Отправка сообщений...', broadcastSent: 'Сообщения успешно отправлены', enterMessage: 'Введите текст сообщения',
  dailyStats: 'Ежедневная статистика', monthlyStats: 'Месячная статистика', userGrowth: 'Рост пользователей', commandStats: 'Статистика команд', peakHours: 'Пиковые часы', last7days: 'Последние 7 дней', last30days: 'Последние 30 дней', newUsers: 'Новые пользователи', activeUsers: 'Активные пользователи', commandsUsed: 'Использовано команд',
  requiredChannels: 'Обязательные каналы', addChannel: 'Добавить канал', channelId: 'ID канала', channelName: 'Название канала', channelLink: 'Ссылка на канал', channelStatus: 'Статус', editChannel: 'Редактировать', deleteChannel: 'Удалить', confirmDeleteChannel: 'Вы хотите удалить канал?', saveChannel: 'Сохранить', noChannels: 'Каналы не найдены',
  coursePrices: 'Цены на курсы', addPrice: 'Добавить цену', courseName: 'Название курса', description: 'Описание', price: 'Цена', currency: 'Валюта', duration: 'Продолжительность (дней)', editPrice: 'Редактировать', deletePrice: 'Удалить', savePrice: 'Сохранить', noPrices: 'Цены не найдены',
  botCommands: 'Команды бота', addCommand: 'Добавить команду', command: 'Команда', descriptionUz: 'Описание (UZ)', descriptionRu: 'Описание (RU)', descriptionEn: 'Описание (EN)', responseUz: 'Ответ (UZ)', responseRu: 'Ответ (RU)', responseEn: 'Ответ (EN)', usageCount: 'Использований', editCommand: 'Редактировать', deleteCommand: 'Удалить', saveCommand: 'Сохранить', noCommands: 'Команды не найдены',
  botSettings: 'Настройки бота', botInfo: 'Информация о боте', adminsList: 'Администраторы', addAdmin: 'Добавить админа', adminName: 'Имя', adminLoginId: 'Логин', adminPassword: 'Пароль', adminTelegram: 'Telegram username', saveSettings: 'Сохранить', settingsSaved: 'Настройки сохранены', deleteAdmin: 'Удалить админа', confirmDeleteAdmin: 'Вы хотите удалить администратора?',
  save: 'Сохранить', edit: 'Редактировать', close: 'Закрыть', loading: 'Загрузка...', error: 'Ошибка', success: 'Успешно', noData: 'Нет данных', refresh: 'Обновить', total: 'Всего', enabled: 'Включено', disabled: 'Отключено', yes: 'Да', no: 'Нет', add: 'Добавить', update: 'Обновить', back: 'Назад', from: 'от', to: 'до', today: 'Сегодня', yesterday: 'Вчера',
};
