export const uz = {
  login: 'Kirish', loginId: 'Login', password: 'Parol', loginButton: 'Kirish', loginError: 'Noto\'g\'ri login yoki parol', loggingIn: 'Kirilmoqda...', adminPanel: 'Admin Panel', botAdminPanel: 'Bot Admin Panel', welcomeBack: 'Xush kelibsiz', enterCredentials: 'Login va parolingizni kiriting',
  dashboard: 'Bosh sahifa', users: 'Foydalanuvchilar', broadcast: 'Ommaviy xabar', statistics: 'Statistika', channels: 'Kanallar', prices: 'Narxlar', commands: 'Buyruqlar', settings: 'Sozlamalar', logout: 'Chiqish',
  totalUsers: 'Jami foydalanuvchilar', activeToday: 'Bugun faol', bannedUsers: 'Bloklangan', messagesSent: 'Xabarlar yuborilgan', recentActivity: 'So\'nggi faoliyat', quickStats: 'Tez statistika', newToday: 'Bugun yangi', totalPayments: 'Jami to\'lovlar',
  searchUsers: 'Qidirish (username, ID)', userId: 'Telegram ID', username: 'Username', firstName: 'Ism', lastName: 'Familiya', status: 'Holat', joinDate: 'Qo\'shilgan', lastActive: 'So\'nggi faollik', actions: 'Amallar', ban: 'Bloklash', unban: 'Blokdan chiqarish', delete: 'O\'chirish', viewDetails: 'Batafsil', banned: 'Bloklangan', active: 'Faol', deleted: 'O\'chirilgan', banReason: 'Bloklash sababi', confirmBan: 'Foydalanuvchini bloklamoqchimisiz?', confirmUnban: 'Foydalanuvchini blokdan chiqarmoqchimisiz?', confirmDelete: 'Foydalanuvchini o\'chirmoqchimisiz?', confirm: 'Tasdiqlash', cancel: 'Bekor qilish', userDetails: 'Foydalanuvchi ma\'lumotlari', totalCommands: 'Jami buyruqlar', language: 'Til', allUsers: 'Barcha', bannedOnly: 'Bloklangan', activeOnly: 'Faol', noUsers: 'Foydalanuvchilar topilmadi', page: 'Sahifa', of: 'dan', previous: 'Oldingi', next: 'Keyingi', showing: 'Ko\'rsatilmoqda', results: 'natija',
  newBroadcast: 'Yangi xabar', messageText: 'Xabar matni', mediaType: 'Media turi', noMedia: 'Media yo\'q', photo: 'Rasm', video: 'Video', document: 'Hujjat', audio: 'Audio', mediaUrl: 'Media URL', captionText: 'Sarlavha (ixtiyoriy)', sendBroadcast: 'Xabar yuborish', broadcastHistory: 'Xabar tarixi', broadcastStatus: 'Holat', pending: 'Kutilmoqda', sending: 'Yuborilmoqda', completed: 'Yakunlandi', failed: 'Xato', sentCount: 'Yuborildi', failedCount: 'Xato', totalRecipients: 'Jami qabul qiluvchilar', broadcastDate: 'Sana', sendingBroadcast: 'Xabar yuborilmoqda...', broadcastSent: 'Xabar muvaffaqiyatli yuborildi', enterMessage: 'Xabar matnini kiriting',
  dailyStats: 'Kunlik statistika', monthlyStats: 'Oylik statistika', userGrowth: 'Foydalanuvchilar o\'sishi', commandStats: 'Buyruqlar statistikasi', peakHours: 'Eng faol soatlar', last7days: 'Oxirgi 7 kun', last30days: 'Oxirgi 30 kun', newUsers: 'Yangi foydalanuvchilar', activeUsers: 'Faol foydalanuvchilar', commandsUsed: 'Buyruqlar ishlatilgan',
  requiredChannels: 'Majburiy kanallar', addChannel: 'Kanal qo\'shish', channelId: 'Kanal ID', channelName: 'Kanal nomi', channelLink: 'Kanal havolasi', channelStatus: 'Holat', editChannel: 'Tahrirlash', deleteChannel: 'O\'chirish', confirmDeleteChannel: 'Kanalni o\'chirmoqchimisiz?', saveChannel: 'Saqlash', noChannels: 'Kanallar yo\'q',
  coursePrices: 'Kurs narxlari', addPrice: 'Narx qo\'shish', courseName: 'Kurs nomi', description: 'Tavsif', price: 'Narx', currency: 'Valyuta', duration: 'Muddat (kun)', editPrice: 'Tahrirlash', deletePrice: 'O\'chirish', savePrice: 'Saqlash', noPrices: 'Narxlar yo\'q',
  botCommands: 'Bot buyruqlari', addCommand: 'Buyruq qo\'shish', command: 'Buyruq', descriptionUz: 'Tavsif (UZ)', descriptionRu: 'Tavsif (RU)', descriptionEn: 'Tavsif (EN)', responseUz: 'Javob (UZ)', responseRu: 'Javob (RU)', responseEn: 'Javob (EN)', usageCount: 'Ishlatilgan', editCommand: 'Tahrirlash', deleteCommand: 'O\'chirish', saveCommand: 'Saqlash', noCommands: 'Buyruqlar yo\'q',
  botSettings: 'Bot sozlamalari', botInfo: 'Bot ma\'lumotlari', adminsList: 'Adminlar', addAdmin: 'Admin qo\'shish', adminName: 'Ism', adminLoginId: 'Login', adminPassword: 'Parol', adminTelegram: 'Telegram username', saveSettings: 'Saqlash', settingsSaved: 'Sozlamalar saqlandi', deleteAdmin: 'Adminni o\'chirish', confirmDeleteAdmin: 'Adminni o\'chirmoqchimisiz?',
  save: 'Saqlash', edit: 'Tahrirlash', close: 'Yopish', loading: 'Yuklanmoqda...', error: 'Xato', success: 'Muvaffaqiyat', noData: 'Ma\'lumot yo\'q', refresh: 'Yangilash', total: 'Jami', enabled: 'Yoqilgan', disabled: 'O\'chirilgan', yes: 'Ha', no: 'Yo\'q', add: 'Qo\'shish', update: 'Yangilash', back: 'Orqaga', from: 'dan', to: 'gacha', today: 'Bugun', yesterday: 'Kecha',
};
